#!/bin/bash

echo "Checking Cloud SQL instance configuration..."
echo ""
echo "Please run these commands in your terminal to check the instance:"
echo ""
echo "1. Get instance IP address:"
echo "   gcloud sql instances describe vault3-db --project=bright-union --format='value(ipAddresses[0].ipAddress)'"
echo ""
echo "2. Check if database 'vault3' exists:"
echo "   gcloud sql databases list --instance=vault3-db --project=bright-union"
echo ""
echo "3. Check if user 'vault3user' exists:"
echo "   gcloud sql users list --instance=vault3-db --project=bright-union"
echo ""
echo "4. Enable public IP access (if needed):"
echo "   gcloud sql instances patch vault3-db --authorized-networks=0.0.0.0/0 --project=bright-union"
echo ""
echo "Or you can check via the Console:"
echo "https://console.cloud.google.com/sql/instances/vault3-db?project=bright-union"
